
image: node:10.5.0

stages:
  - install_dependencies
  - lint
  - test
  - build

install_dependencies:
  tags:
    - golang
    - linux
  stage: install_dependencies
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

lint:
  tags:
    - golang
    - linux
  stage: lint
  script:
    - npm run lint

test:
  tags:
    - golang
    - linux
  stage: test
  script:
    - npm run test:ci

build:
  tags:
    - golang
    - linux
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
    - build/
